Repository craft-ai/craft-ai-client-js, pull requests merged in 2020-10, with the labels that each got.

#203 Bulk generator JS client
  CHANGELOG.md
  package-lock.json
  package.json
  src/client.js
  src/polyfill.js
  test/test_addAgentContextOperations.js
  test/test_bulk.js
  test/test_getAgentContextOperations.js
  test/test_getAgentDecisionTree.js
  test/test_getAgentStateHistory.js
  test/test_getGeneratorContextOperations.js
  test/test_missing_values.js
Labels: feature

#212 Fix/tests ids
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
  test/test_addAgentContextOperations.js
  test/test_bulk.js
  test/test_createGenerator.js
  test/test_getAgentDecisionTree.js
Labels: bug

#210 Add a clean_up session after test round on travis
  .travis.yml
  package.json
  scripts/clean_up.js
Labels: chore
